### ISSUE TITLE
awt and data-awareness-level inverted

### ISSUE THREAD

**Issue by andrea75** [palsoft333/meteoalarm.org#1]
Hi, and thank you so much for your work! I noticed that sometimes, awt and data-awareness-level are inverted. For example, today for Italy, this was the alarm:

`    <item>
      <title>Liguria</title>
      <description><![CDATA[<table border="0" cellspacing="0" cellpadding="3"><tr><th colspan="3" align="left">Today</th></tr><tr><th colspan="3" align="left"><br />Tomorrow</th></tr><tr><td data-awareness-level="2" data-awareness-type="10" width="28">awt:10 level:2</td><td><b>From: </b><i>2024-11-26T00:00:00+00:00</i><b> Until: </b><i>2024-11-26T23:59:00+00:00</i></td></tr><tr><td width="28"></td><td>English(en-GB): Moderate intensity weather phenomena expected E part  (DISCLAIMER: "Information provided on METEOALARM for Italy regard only the intensity and recurrence of the phenomena, further details can be found at www.meteoam.it. METEOALARM information do not provide the assessment of impact on the territory and they do not represent the Official Alerts messages that are issued by the National Civil Protection Service https://www.protezionecivile.gov.it") BE AWARE, keep up to date with the latest weather forecast. Expect some minor disruption to outdoor activities
Italian(it-IT): Sono previsti fenomeni meteorologici di moderata intensità levante  (DISCLAIMER: "Le informazioni fornite su METEOALARM per l'Italia riguardano esclusivamente l'intensità e la ricorrenza dei fenomeni, maggiori dettagli sono disponibili su www.meteoam.it. Le informazioni METEOALARM non forniscono la valutazione di impatto sul territorio e non rappresentano i messaggi di Allerta Ufficiali che vengono emessi dal Servizio Nazionale di Protezione Civile https://www.protezionecivile.gov.it") STARE (RIMANERE) ATTENTI. Tenersi aggiornati con le previsioni del tempo più recenti. Aspettarsi alcuni disagi minori per le attività all'aria aperta.</td></tr></table>]]></description>
      <pubDate>Mon, 25 Nov 24 08:10:37 +0000</pubDate>
      <link>https://meteoalarm.org?geocode=EMMA_ID:IT007</link>
      <guid isPermaLink="false">d1ba3d3b43044a1b07d050341790a472</guid>
    </item>`

But the script put "**2**" as data-awareness-type and "**10**" as level. Thank you!

**Comment by palsoft333** [comment]
Hello, thank you for your report. At first, Meteoalarm did it wrong and flipped these two entities between each other, so I have to change them in the code. Now it seems to be fixed at their side, so I have updated the code likewise.
